spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/traver
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource

  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp

  devtools:
    restart:
      enabled: true
    additional-paths:
      - src/main/java
      - src/main/resources
      - src/main/resources/static/image
      - src/main/webapp/image
    trigger-file: '*.class,*.properties,*.jpg,*.png'

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB